---
name: 'sst-diff-action'
description: |
  Github action that will compile an sst diff and write it to
  the action summary.
author: 'Kodehort'
inputs:
  stage:
    required: true
    description: 'The stage you wish to run the diff against'
runs:
  using: 'node16'
  main: 'dist/main.cjs'
branding:
  icon: 'code'
  color: 'gray-dark'
