---
name: 'build-test'
# rebuild any PRs and main branch changes
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # make sure build/ci work properly
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 16.x
      - run: |
          pnpm install
      - run: |
          pnpm run all
  # make sure the action works on a clean machine without building
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          mkdir -p .sst/dist
          touch .sst/dist/manifest.json
          echo '{"version": "31.0.0","artifacts": {}}' > .sst/dist/manifest.json
          touch sst.config.ts
      - uses: ./
        with:
          stage: production
